name: build and sign App Store IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ipa:
    runs-on: macos-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install Node dependencies
        run: npm ci

      - name: build web project
        run: npm run build

      - name: sync build
        run: npx cap sync ios

      - name: setup Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app
          sudo xcodebuild -version

      - name: set up provisioning profile and certificates
        env:
          CERTS_KEY: ${{ secrets.IOS_P12_BASE64_ENCODED }}
          CERTS_PASSWORD: ${{ secrets.IOS_P12_PASSWORD }}
          PROVISIONING_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64_ENCODED }}
        run: |
          # decode certificates
          echo "$CERTS_KEY" | base64 --decode > certificates.p12
          echo "$PROVISIONING_PROFILE" | base64 --decode > provisioning.mobileprovision
          
          # create temporary keychain
          security create-keychain -p "" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          security unlock-keychain -p "" build.keychain

          # import certificate to keychain
          security import certificates.p12 -k build.keychain -P "$CERTS_PASSWORD" -T /usr/bin/codesign
          security default-keychain -s build.keychain
          
          security find-identity -p codesigning -v

          # move provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          mv provisioning.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: build IPA
        run: |
          xcodebuild -workspace './ios/App/App.xcworkspace' \
            -scheme App \
            -sdk iphoneos \
            -destination generic/platform=iOS \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive \
            archive

      - name: export IPA
        working-directory: ios/App
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/App.xcarchive \
            -exportPath $PWD/build \
            -exportOptionsPlist exportOptions.plist

      - name: upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-store-ipa
          path: ios/App/build/App.ipa
